// bug-tracker-vue/src/components/LoginForm.vue
<template>
  <div class="login-container">
    <div class="account-form">
      <h3 class="title is-3"><strong>Log in</strong></h3>
      <div class="field mb-4">
        <input type="text" name="username" class="input"
          placeholder="Enter username" v-model="user.username" @keydown="resetMessage" />
      </div>
      <div class="field">
        <input type="password" name="password" class="input" placeholder="Enter password" v-model="user.password" @keydown="resetMessage" />
      </div>
      <button class="button is-primary is-fullwidth mt-5 mb-5" @click="login">Login</button>
      <router-link :to="{name: 'RegisterForm', params: {isAnimated: false}}">
        <a @click="emitAnimationData" class="hover-light">Dont have an account with us? Register</a>
      </router-link>
    </div>
  </div>
</template>

<script>
import jwtserializer from '../scripts/jwt-serializer';

export default {
  name: 'LoginFormComponent',
  props: {
    isAnimated: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      user: {
        username: undefined,
        password: undefined,
      },
    };
  },
  methods: {
    resetForm() {
      this.user.username = undefined;
      this.user.password = undefined;
    },
    resetMessage() {
      this.$emit('error', '');
    },
    setMessage(message) {
      this.$emit('error', message);
    },
    emitAnimationData() {
      this.$emit('animate', this.isAnimated);
    },
    async login() {
      fetch('http://localhost:3002/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: this.user.username,
          password: this.user.password,
        }),
      })
        .then((res) => {
          res.json().then((data) => {
            console.log(data);
            this.resetForm();
            jwtserializer.storeJwt(data.accessToken);
            jwtserializer.storeRefresh(data.refreshToken);
            this.$router.push({ name: 'main' });
          });
        })
        .catch(() => {
          this.resetForm();
          this.setMessage('Something Went Wrong, Try Again!');
        });
    },
  },
};
</script>

<style lang="scss" scoped>
</style>

// bug-tracker-ng/src/app/auth/login-form/login-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { User } from 'src/app/models/user';
import { AuthMessagingService } from './../auth-messaging.service';
import { AuthService } from './../auth.service';

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.scss']
})

export class LoginFormComponent implements OnInit {
  isAnimated: boolean;

  user = new FormGroup({
    username: new FormControl(),
    password: new FormControl()
  });

  constructor(
    private routerActive: ActivatedRoute, 
    private authMessagingService: AuthMessagingService, 
    private authService: AuthService,
    private router: Router) { }

  ngOnInit(): void {
    this.setMessage('');
    this.isAnimated = this.routerActive.snapshot.queryParams["isAnimated"];
  }

  handleLogin() {
    const userObj: User = {
      username: this.user.value.username,
      password: this.user.value.password
    };

    this.authService.loginUser(userObj).subscribe(
      (res) => {
        this.router.navigate(['bugs']);
      },
      (err) => {
        return this.setMessage("Wrong Username Or Password");
      } 
    );
  }

  resetForm() {
    this.user = undefined;
  };

  resetMessage() {
    this.authMessagingService.setMessage('');
  };

  setMessage(message) {
    this.authMessagingService.setMessage(message);
  };

  emitAnimationData() {
    this.authMessagingService.setAnimationState(this.isAnimated);
  };
}

<div class="login-container">
  <form [formGroup]="user" class="account-form">
    <h3 class="title is-3"><strong>Log in</strong></h3>
    <div class="field mb-4">
      <input 
        formControlName="username"
        type="text"
        name="username"
        class="input"
        placeholder="Enter username"
        v-model="user.username"
        (keydown)="resetMessage()"
      />
    </div>
    <div class="field">
      <input
        formControlName="password"
        type="password"
        name="password"
        class="input"
        placeholder="Enter password"
        v-model="user.password"
        (keydown)="resetMessage()"
      />
    </div>
    <button
      class="button is-primary is-fullwidth mt-5 mb-5"
      (click)="handleLogin()"
    >
      Login
    </button>
    <a
      [routerLink]="['../register']"
      [queryParams]="{ isAnimated: false }"
      (click)="emitAnimationData()"
      class="hover-light"
      >Dont have an account with us? Register
    </a>
  </form>
</div>
