// bug-tracker-ng/src/app/bugs/bug-card/bug-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { faBug, faEdit, faComment } from '@fortawesome/free-solid-svg-icons';
import { Bug } from '../../models/bug';
import { BugModalStateService } from '../../bug-modal-state.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bug-card',
  templateUrl: './bug-card.component.html',
  styleUrls: ['./bug-card.component.scss']
})
export class BugCardComponent {
  @Input() bug: Bug;

  faBug = faBug;
  faEdit = faEdit;
  faComment = faComment;

  constructor(private modalService: BugModalStateService, private router: Router) { }

  setBugColour() {
    if(this.bug.status === "Created") {
      return { 'has-text-danger': true }
    }
    if(this.bug.status === "In-Progress") {
      return { 'has-text-warning': true }
    }
    if(this.bug.status === "Fixed") {
      return { 'has-text-success': true }
    }
  }

  handleEditClick() {
    this.modalService.openModal();
    this.router.navigate([`bugs/edit`], { state: { bugId: this.bug._id }});
  }
}

<div class="card">
  <header class="card-header">
    <a class="card-header-icon">
      <span class="icon" [class]="setBugColour()">
        <fa-icon [icon]="faBug" class="fa-2x"></fa-icon>
      </span>
    </a>
    <div class="container has-text-right mt-2 mr-2">
      <button (click)="handleEditClick()" class="button is-small" align="right">
        <fa-icon [icon]="faEdit"></fa-icon>
      </button>
    </div>
  </header>
  <div class="block">
    <br />
  <div class="block mx-2">
    <app-tag-list [bug]="bug"></app-tag-list>
  </div>
  <h2 class="card-header-title">
    {{ bug.name | titlecase }}
  </h2>
  </div>
  <footer class="card-footer">
    <span class="icon">
      <fa-icon [icon]="faComment"></fa-icon>
    </span>
    {{ bug.comments.length }}
    <span class="container has-text-right"> 
      <time datetime="2016-1-1">{{ bug.date | date }}</time>
    </span>
  </footer>
</div>

// bug-tracker-vue/src/components/BugCard.vue
<template>
  <div class="card">
  <header class="card-header">
    <p class="card-header-title">
      {{bug.name}}
    </p>
    <div class="card-header-icon">
      <span class="icon" :class="statusObject()">
        <i class="fas fa-bug" ></i>
      </span>
    </div>
  </header>
  <div class="card-content">
    <div class="content">
      {{bug.description}}
      <br>
      <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
    </div>
  </div>
  <footer class="card-footer">
      <i class="fas fa-comments mr-1"></i>
      {{bug.comments.length}}
  </footer>
</div>
</template>

<script>
export default {
  props: [
    'bug',
    'status'
  ],
  methods: {
    statusObject() {
      if (this.status === 'Created') {
        return {
          'has-text-danger': true
        };
      }
      if (this.status === 'In-Progress') {
        return {
          'has-text-warning': true
        };
      }
      if (this.status === 'Fixed') {
        return {
          'has-text-success': true
        };
      }
    }
  }
};
</script>

<style lang="scss" scoped>
@import '../assets/styles/main.scss';
.card-header-title {
    color: $text;
}

.card {
  background-color: rgb(66,66,66);
  margin-bottom: 10px;
}
.card-footer {
    padding: 10px
}

.card-header-icon {
  cursor: default !important;
}
</style>
