// bug-tracker-ng/src/app/navbar/navbar.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import { AuthService } from './../auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {
  @Input() username: string;

  faSignOutAlt = faSignOutAlt;

  constructor(private authService: AuthService, private router: Router) { }

  ngOnInit(): void {
  }

  logoutHandler() {
    this.authService.logoutUser().subscribe(() => {
      this.router.navigate(['auth/login']);
    })
  }
}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="../assets/img/BugtraceLogo.gif" alt="" width="150">
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item mr-2">
      <!-- <Badge :name="username"/> -->
      <div>Hi {{ username }}!</div>
    </div>

    <div class="navbar-item mr-2">
      <div class="buttons">
        <a (click)="logoutHandler()" class="button is-small is-danger is-outlined">
          <fa-icon [icon]="faSignOutAlt" class="mr-1"></fa-icon>Logout
        </a>
      </div>
    </div>
  </div>
</nav>

// bug-tracker-vue/src/components/Navbar.vue
<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="../assets/img/BugtraceLogo.gif" alt="" width="150">
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item mr-2">
      <Badge :name="username"/>
      <div>Hi {{ username }}!</div>
    </div>

    <div class="navbar-item mr-2">
      <div class="buttons">
        <a @click="logoutHandler" class="button is-small is-danger is-outlined">
          <i class="fas fa-sign-out-alt mr-1"></i>Logout
        </a>
      </div>
    </div>
  </div>
</nav>
</template>

<script>
// import SocialLinks from './SocialLinks.vue';
import Badge from './Badge.vue';

export default {
  components: {
    Badge
    // SocialLinks
  },
  props: {
    username: {
      type: String,
      required: true
    }
  },
  methods: {
    logoutHandler() {
      this.$store.dispatch('logout')
        .then(() => {
          this.$router.push({ name: 'loginForm' });
        });
    }
  }
};
</script>

<style lang="scss" scoped>
@import '../assets/styles/main.scss';

.navbar {
  background: $background-secondary;
}

.navbar-item {
  padding: 0px;
  max-height: 300;
}

.navbar-item img {
  max-height: 100%;
}

</style>
