// bug-tracker-ng/src/app/shared/navbar/navbar.component.ts
import { Component, Input, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';
import { UserService } from './../user.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  faSignOutAlt = faSignOutAlt;

  constructor(private authService: AuthService, private router: Router, private userService: UserService) { }

  user$ = this.userService.getUser();

  logoutHandler() {
    this.authService.logoutUser().subscribe(() => {
      this.router.navigate(['auth/login']);
    })
  }
}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="../assets/img/BugtraceLogo.gif" alt="" width="150" />
    </a>
    <a
      role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-end" *ngIf="user$ | async as user">
    <div class="navbar-item mr-2">
      <div>Hi {{ user.username | titlecase }}!</div>
    </div>

    <div class="navbar-item mr-2">
      <div class="buttons">
        <a
          (click)="logoutHandler()"
          class="button is-small is-danger is-outlined"
        >
          <fa-icon [icon]="faSignOutAlt" class="mr-1"></fa-icon>Logout
        </a>
      </div>
    </div>
  </div>
</nav>

// bug-tracker-vue/src/components/Navbar.vue
<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="../assets/img/BugtraceLogo.gif" alt="" width="150">
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item mr-2">
      <div>Hi {{ username }}!</div>
    </div>

    <div class="navbar-item mr-2">
      <div class="buttons">
        <a class="button is-small is-danger is-outlined"><i class="fas fa-sign-out-alt mr-1"></i>Logout</a>
      </div>
    </div>
  </div>
</nav>
</template>

<script>
// import SocialLinks from './SocialLinks.vue';

export default {
  components: {
    // SocialLinks
  },
  props: {
    username: {
      type: String,
      required: true
    }
  },
};
</script>

<style lang="scss" scoped>
@import '../assets/styles/main.scss';

.navbar {
  background: $background-secondary;
}

.navbar-item {
  padding: 0px;
  max-height: 300;
}

.navbar-item img {
  max-height: 100%;
}

</style>
