// bug-tracker-ng/src/app/auth/register-form/register-form.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { AuthMessagingService } from './../auth-messaging.service';
import { Router } from '@angular/router';
import { AuthService } from '../../shared/auth.service';
import { User } from '../../models/user';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss']
})
export class RegisterFormComponent implements OnInit, OnDestroy {
  isAnimated: boolean;
  userSub: Subscription;

  user = new FormGroup({
    username: new FormControl(),
    password: new FormControl()
  });

  constructor(private authMessagingService: AuthMessagingService, private router: Router, private authService: AuthService, private routerBasic: Router) { }

  ngOnInit(): void {
    this.setMessage('');
    this.authMessagingService.getAnimationState().subscribe((anim) => {
      this.isAnimated = anim;
    });
  }

  handleRegistration() {
    const userObj: User = {
      username: this.user.value.username,
      password: this.user.value.password
    };

    this.userSub = this.authService.registerUser(userObj).subscribe(() => {
        this.authMessagingService.setAnimationState(true);
        this.routerBasic.navigate(['auth/login']);
        this.resetForm();
      },
      (err) => {
        this.setMessage('Sorry, this username is already taken!');
      }
    );
  }

  resetForm() {
    this.user = undefined;
  };

  resetMessage() {
    this.authMessagingService.setMessage('');
  };

  setMessage(message) {
    this.authMessagingService.setMessage(message);
  };

  emitAnimationData() {
    this.authMessagingService.setAnimationState(false);
    this.router.navigate(['/auth/login']);
  };

  ngOnDestroy(): void {
    if (this.userSub) {
      this.userSub.unsubscribe();
    }
  }
}


<div class="login-container">
  <form [formGroup]="user" class="account-form">
    <h3 class="title is-3"><strong>Register</strong></h3>
    <div class="field mb-4">
      <input
        formControlName="username"
        type="text"
        name="username"
        class="input"
        placeholder="Enter username"
        v-model="user.username"
        (keydown)="resetMessage()"
      />
    </div>
    <div class="field">
      <input
        formControlName="password"
        type="password"
        name="password"
        class="input"
        placeholder="Enter password"
        v-model="user.password"
        (keydown)="resetMessage()"
      />
    </div>
    <button
      class="button is-primary is-fullwidth mt-5 mb-5"
      (click)="handleRegistration()"
    >
      Register
    </button>
    <a
      (click)="emitAnimationData()"
      class="hover-light"
      >Already Have An Account? Login!
    </a>
  </form>
</div>

// bug-tracker-vue/src/components/RegisterForm.vue
<template>
  <div class="login-container">
    <div class="account-form">
      <h3 class="title is-3"><strong>Register</strong></h3>
      <div class="field mb-4">
        <input type="text" name="username" class="input" placeholder="Enter username" v-model="user.username" @keydown="resetMessage"/>
      </div>
      <div class="field">
        <input type="password" name="password" class="input" placeholder="Enter password" v-model="user.password" @keydown="resetMessage"/>
      </div>
      <button value="Register" class="button is-primary is-fullwidth mt-5 mb-5" @click="handleRegister">Register</button>
      <router-link :to="{name: 'loginForm', params: { isAnimated: false }}">
        <a @click="emitAnimationData" class="hover-light">Already have an account?</a>
      </router-link>
    </div>
  </div>
</template>

<script>
import authformmixin from '../mixins/auth-form-mixin';

export default {
  name: 'RegisterFormComponent',
  mixins: [authformmixin],
  methods: {
    handleRegister() {
      console.log('Just Once');
      this.$store.dispatch('register', this.user)
        .then(() => {
          this.$router.push({ name: 'loginForm' });
          this.resetForm();
        })
        .catch((err) => {
          console.log(err);
          this.resetForm();
          this.setMessage('That Username Is Already Taken');
        });
    }
  },
};
</script>

<style lang="scss" scoped>
</style>
